# Generated by Django 4.1.7 on 2023-02-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bus_dest_destination_guestdetail_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='dest',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
