# Generated by Django 4.1.7 on 2023-02-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bus_image_alter_dest_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='Hotels',
        ),
    ]
