# Generated by Django 4.1.7 on 2023-02-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_hotel_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
