# Generated by Django 4.1.7 on 2023-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=500)),
            ],
        ),
    ]
