# Generated by Django 4.0.4 on 2023-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_notifi'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_name', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('DEL', 'DELURE'), ('KIN', 'KING'), ('QUE', 'QUEEN')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
