# Generated by Django 4.0.4 on 2023-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_feedback_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Hotel_name',
            new_name='name',
        ),
    ]
